project:
  type: book

book:
  title: "Zbiór zadań - Java"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pl
  pdf:
    lang: pl
    documentclass: scrreprt

editor: visual

