project:
  type: book

book:
  title: "Zbiór zadań - Java"
  author: Piotr Jastrzębski
  date: today
  chapters:
    - index.qmd
    - part: "Wprowadzenie do języka Java"
      chapters: 
        - wejsciewyjscie.qmd
        - instrukcjewarunkowe.qmd
        - petle.qmd
    - part: "Programowanie obiektowe"
      chapters:
        - klasaobiekt.qmd
        - modyfikatorydostepu.qmd
        - konstruktor.qmd
        - zlozonepolawklasie.qmd
        - dziedziczenie.qmd
        - klasyabstrakcyjne.qmd
        - comparable.qmd
        - comparator.qmd
        - kopiowanie.qmd
    - part: "Zadania różne"
    - part: "Wzorce projektowe"
    - references.qmd
  downloads: pdf


bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pl
  pdf:
    lang: pl

editor: visual

