project:
  type: book

book:
  title: "Zbiór zadań - Java"
  author: Piotr Jastrzębski
  date: today
  chapters:
    - index.qmd
    - part: "Wprowadzenie do języka Java"
      chapters: 
        - wejsciewyjscie.qmd
    - part: "Programowanie obiektowe"
      chapters:
        - konstruktor.qmd
        - dziedziczenie.qmd
    - references.qmd
  downloads: pdf
  repo-url: https://github.com/pjastr/zbior-zadan-java
  repo-actions: [issue]


bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pl
  pdf:
    lang: pl
    documentclass: scrbook

editor: visual

