project:
  type: book

book:
  title: "Zbiór zadań - Java"
  author: Piotr Jastrzębski
  chapters:
    - index.qmd
    - references.qmd
  downloads: [ pdf, epub ]

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: pl
  pdf:
    lang: pl
    documentclass: scrreprt
  epub:
    lang: pl

editor: visual

