project:
  type: book

book:
  title: "Zbiór zadań - Java"
  author: Piotr Jastrzębski
  date: today
  cover-image: logo-java.jpg
  chapters:
    - index.qmd
    - part: "Wprowadzenie do języka Java"
      chapters: 
        - wejsciewyjscie.qmd
        - instrukcjewarunkowe.qmd
        - petle.qmd
        - metody.qmd
        - random.qmd
        - tablice.qmd
        - arraylist.qmd
        - napisy.qmd
    - part: "Programowanie obiektowe"
      chapters:
        - klasaobiekt.qmd
        - modyfikatorydostepu.qmd
        - konstruktor.qmd
        - static.qmd
        - rekord.qmd
        - tostringeqauls.qmd
        - dziedziczenie.qmd
        - pakiety.qmd
        - zlozonepolawklasie.qmd
        - klasyabstrakcyjne.qmd
        - final.qmd
        - comparable.qmd
        - comparator.qmd
        - kopiowanie.qmd
        - interfejsy.qmd
        - delegacje.qmd
    - part: "Zadania różne"
    - part: "Wzorce projektowe"
    - references.qmd
  downloads: pdf
  repo-url: https://github.com/pjastr/zbior-zadan-java
  repo-actions: [issue]


bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: pl
  pdf:
    lang: pl
    header-includes: |
      \titlehead{\includegraphics[width=6in]{logo-java.jpg}}


editor: visual

