# Pętle

(1) Napisz program, który wykorzystując pętlę `for` wyświetli liczby od 1 do 100.

(2) Napisz program, który przy użyciu pętli `while` obliczy sumę liczb od 1 do 50.

(3) Napisz program w Javie, który za pomocą pętli `for` generuje pierwsze 10 liczb ciągu Fibonacciego.

(4) Stwórz program, który używając zagnieżdżonych pętli `for`, wyświetli tabliczkę mnożenia dla liczb od 1 do 10.

(5) Napisz program, który używając pętli `do-while`, wyświetli pierwsze 20 liczb parzystych i nieparzystych.

(6) Napisz program, który sprawdzi, czy podana liczba jest liczbą pierwszą. Liczba powinna być wprowadzona przez użytkownika.

(7) Napisz program, który oblicza sumę cyfr dowolnej wprowadzonej liczby. Program powinien akceptować liczbę jako input od użytkownika.

(8) Napisz program, który generuje i wyświetla pierwsze 10 elementów szeregu geometrycznego o zadanym pierwszym elemencie i ilorazie. Parametry szeregu powinny być wprowadzane przez użytkownika.

(9) Stwórz program, który przyjmie od użytkownika liczbę całkowitą i zwróci tę liczbę w odwrotnej kolejności. Na przykład, dla liczby 12345, wynik powinien wynosić 54321. Możesz ograniczyć program tylko do liczb dodatnich.

(10) Napisz program, który obliczy sumę kwadratów liczb od 1 do n, gdzie n jest liczbą wprowadzoną przez użytkownika.

(11) Napisz program, który znajdzie i wyświetli wszystkie liczby doskonałe mniejsze od 10 000. Liczba doskonała to taka, której suma dzielników (bez niej samej) jest równa jej wartości. Na przykład, 6 jest liczbą doskonałą, ponieważ $1 + 2 + 3 = 6$.

(12) Napisz program, który znajdzie wszystkie liczby Amstronga mniejsze od 10 000. Liczba Amstronga to taka, której suma jej cyfr podniesionych do potęgi równiej liczbie cyfr w tej liczbie, jest równa samej liczbie. Na przykład 153 jest liczbą Amstronga, ponieważ $1^3 + 5^3 + 3^3 = 153$.

(13) Napisz program, który dla dwóch podanych liczb obliczy ich najmniejszą wspólną wielokrotność (NWW). Użytkownik powinien podać dwie liczby jako dane wejściowe.

(14) Napisz program pobierający z klawiatury liczbę całkowitą dodatnią. Następnie narysuj odpowiedni trójkąt np. dla 5:

```         
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5
```

15. Napisz program, który pobiera od użytkownika liczbę naturalną $n$ ($n\geqslant 0$). Następnie wyznacz i wyświetl $n$-ty element ciągu:

a)  $(4,-8,16,-32,64,\ldots )$
b)  $(2,6,18,54,162,\ldots )$
c)  $(8,3,-2,-7,-12,\ldots )$

16. Napisz program wczytujący kolejne liczby całkowite (różnych znaków) z klawiatury i kończący się gdy ich suma przekroczy 100.

17. Napisz program, który pobiera od użytkownika dodatnią liczbę całkowitą $n$, następnie $n$ liczb całkowitych $a_1, \ldots, a_n$. Program ma wyświetlić ile spośród tych liczb spełnia warunek $3^k < a_k <k!$ dla $1\leq k \leq n$.

18. Napisać program wyświetlający na ekranie pierwsze szesnaście potęg dwójki. Wykorzystaj w tym celu pętle.

19. Napisz program, który pobiera od użytkownika 5 liczb całkowitych. Pobieranie ma zostać przerwane, gdy użytkownik wprowadzić liczbę ujemną. Jeśli pobieranie nie zostanie przerwane, wyświetl sumę wprowadzonych liczb.

20. Napisz program, który wczytuje ze standardowego wejścia dwie liczby całkowite $n$ i $m$ (zakładamy, że $n < m$) i wypisuje na standardowym wyjściu wartość liczby $n\cdot \ldots \cdot m$.

21. Napisz program, który wczytuje ze standardowego wejścia dwie liczby całkowite $n$ i $m$ (zakładamy, że $n < m$) i wypisuje na standardowym wyjściu wartość liczby $n+ \ldots + m$.

22. Napisz program, który pobiera od użytkownika trzy liczby całkowite $a, b, c$. Program ma wyświetlić informację, czy liczby są uporządkowane nierosnąco w kolejności ich wprowadzania lub nie.

23. Napisz program, który pobiera od użytkownika trzy liczby całkowite $a, b, c$. Program ma sprawdzić, czy b jest większa niż minimum z pozostałych liczb. Wyświetl komunikat słowny czy warunek jest lub nie jest spełniony.

24. Napisz program, który pobiera od użytkownika trzy dodatnie liczby całkowite $a, b, c$. Na standardowym wyjściu wyświetl dodatnie liczby całkowite większe od $b$, mniejsze lub równe od $a$ i podzielne przez $c$.

25. Napisz program, który ze standardowego wejścia pobiera liczbę naturalną $a$ a następnie wypisuje na standardowym wyjściu ile z cyfr liczby $a$ jest równe 7.

26. Napisać program, który wczyta z wejścia liczby całkowite aż do napotkania liczby ujemnej, a następnie wyświetla największy oraz najmniejszy element z wczytanych liczb (z pominięciem ostatniej, ujemnej liczby).
